name: poc_kingpower
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_form_builder: ^9.2.1
  flutter_screen_lock: ^9.0.2
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7
  supabase_flutter: ^2.5.3
  flutter_screenutil: ^5.9.0
  go_router: ^13.2.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  multiple_result: ^5.1.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  equatable: ^2.0.5
  # screenshot: ^3.0.0
  # https://pub.dev/packages/retrofit
  retrofit: ^4.0.1
  # https://pub.dev/packages/dio
  dio: ^5.3.2
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.2.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  json_serializable: "^6.8.0"
  freezed: ^2.5.2
  flutter_gen_runner: ^5.4.0
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
